kagkarlsson/db-scheduler

README.md

Links stopped working after restructuring to db-scheduler core module. Change to relative paths instead of full URLs.

Fix dead links to table definitions

---

NOTICE
README.md
db-scheduler-boot-starter/pom.xml
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerProperties.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerStarter.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/startup/AbstractSchedulerStarter.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/startup/ContextReadyStart.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/startup/ImmediateStart.java
pom.xml

This PR resolves #70 by introducing a new configuration property: `db-scheduler.start-scheduler-immediately`.
Existing behaviour is enabled by default (`true`). However, if it is set to `false` the scheduler will start after the Spring context is ready/refreshed ([`ContextRefreshedEvent`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/event/ContextRefreshedEvent.html)).

Configurable scheduler start

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java

This patch now only depends on the HealthIndicator class being present
on the classpath and delegates the responsibility of using the indicator
and registering it with a registry to Spring Boot itself.
Depending on a HealthIndicatorRegistry bean was a naive approach. In
Spring Boot 2.2.0, HealthIndicatorRegistry is deprecated in favor of
HealthContributorRegistry.
This approach has been tested with Spring Boot 2.1.10 and 2.2.1.

Spring Boot: Fix health check in 2.2.x

---

README.md
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java

To follow Spring best practices and give a possibility to disable/enable health indicator @ConditionalOnEnabledHealthIndicator was introduced

Add @ConditionalOnEnabledHealthIndicator

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java

When multiple tasks are scheduled and something goes wrong with them, it could be useful to know which ones failed.

Log task name on failure

---

db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/SchedulesTest.java

A test outcome in `SchedulesTest.java` depends on JVM time zone. 
Fixed to specify the time zone in the assert.

Specify timezone in Schedules test

---

README.md

`<nr-of-threads>` is not showing up in the Readme

fix small types in Readme

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/TestTasks.java

I have a use case where I need to reschedule a task, but with different data. `TaskRepository` already has this capability, so this PR just introduces a new method on the `Scheduler` and `SchedulerClient`.
Please let me know if this makes sense, or if you want me to change anything. Thanks!

allow rescheduling task with new data

---

db-scheduler/pom.xml
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerName.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/ClusterTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/EmbeddedPostgresqlExtension.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutoCommitPostgresqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/DeadExecutionTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ExecutorPoolTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ImmediateExecutionTest.java
pom.xml

db-scheduler was relying on autoCommit being enabled on the connections from the underlying `DataSource` as described in #97 . Now `commit` is called explicitly when `autoCommit=false`

Commit explicitly if auto-commit=false. Add compatibility test for such data-source.

---

README.md
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerProperties.java
db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
pom.xml

Added public constants to `SchedulerBuilder`. When utilizing those constants the defaults in the starter will always be in sync the db-scheduler library. I've also bumped of Spring Boot to verify that we're good with the latest version.

Spring Boot: Adjust defaults to align with main library

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleOnceOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleRecurringOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/Tasks.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/Daily.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/FixedDelay.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/Schedule.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/RecurringTaskTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleRecurringOnStartupTest.java

If a `Schedule` for a `RecurringTask` is updated, update the future execution with the new execution-time to avoid having to wait for the execution to run to have execution-times based on new `Schedule`.
* For _deterministic_  schedule (Cron, Daily), update future execution for all changes
* For _non-deterministic_  schedule (FixedDelay), update future execution only if new execution-time is closer to `now()`

Update existing execution for recurring task if schedule changes to more frequent

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
pom.xml

Since we already depend on Spring Boot 2.2+ (and using 2.3.x), I've took the liberty to modifiy the autoconfiguration to not depend on deprecated classes. Spring Boot 2.4 is scheduled for November 2020 and will remove deprecations from 2.2.0 (including `HealthIndicatorAutoConfiguration`).
See https://github.com/spring-projects/spring-boot/issues/22034

Fix Spring Boot 2.2.0 deprecation (2.4.0 is coming)

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java

I noticed while debugging something else that the [`AutodetectJdbcCustomization constructor`](https://github.com/kagkarlsson/db-scheduler/blob/89626e6d1942d5e8ba6df4cdb758c72c50f0aa27/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java#L34) is initialized by the builder every time, even if `JdbcCustomization` is already set. Since the constructor performs interactions with the DB it is better to put this in `orElseGet()` to prevent it unless needed.

Don't run AutodetectJdbcCustomization unless needed

---

README.md
db-scheduler/pom.xml
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/ManualScheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/CustomTableNameTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MysqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutoCommitPostgresqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Oracle11gCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/PostgresqlCompatibilityTest.java
examples/spring-boot-example/src/test/java/com/github/kagkarlsson/examples/boot/SmokeTest.java

For SchedulerClient, change default behavior to not commit when datasource has autocommit=false to allow for external transaction-managers, like Spring.
This bug was introduced in version 7.1.

Configurable commit behavior for when autocommit=false

---

db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ScheduledExecution.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ScheduledExecutionsFilter.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/TaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AndCondition.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/QueryBuilder.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/UnresolvedTaskMain.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ExecutorPoolTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/jdbc/QueryBuilderTest.java
pom.xml

* Change `getScheduledExecutions(..)` to return `List<..>` instead of taking a `Consumer`.
* The `Consumer` variant is renamed to `fetchScheduledExecution`.
* Introduce a `ScheduledExecutionsFilter` for `getScheduledExecutions(..)` to allow specifying whether or not to return picked executions

Scheduler client improvements

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/DefaultJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MssqlJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/PostgreSqlJdbcCustomization.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/jdbc/PostgreSqlJdbcCustomizationTest.java

Fixes behaviour described in https://github.com/kagkarlsson/db-scheduler/issues/164

Use explicit LIMIT in scheduler task polling query for PostgreSQL

---

db-scheduler-boot-starter/pom.xml
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java

Default java serializer does not work correctly with Spring Boot Devtools. During deserialization `ClassCastException`s are thrown. That is because `ObjectInputStream` does not use correct class loader (classloaders in devtools are more complicated). See: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-known-restart-limitations

Spring Boot Devtools-friendly default task data serializer

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/CompletionHandler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/Task.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/OneTimeTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java

Small contribution. Basically adding some more informative toString implementations to:
- `CronSchedule`, because it was missing. Already present in Daily and FixedDelay.
- Task implementations: adds the _type_ of task (RecurringTask, OneTimeTask etc), and also try to output some information about rescheduling from RecurringTask.
- Keeping the toString in `Task` to have a base toString for custom derivations from Task. Small fix from `task=` to `name=` to align with what seemed to be the existing style/format.
As the toString implementation for RecurringTask may seem a little... assuming perhaps (?), I am open to suggestions on how to better structure it, if you see any problems with it.
A bit on the side, but I also wanted to bring [ThreeTen …

Add some toStrings to 

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/FailureHandler.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
examples/features/src/main/java/com/github/kagkarlsson/examples/ExponentialBackoffMain.java
examples/features/src/main/java/com/github/kagkarlsson/examples/ExponentialBackoffWithMaxRetriesMain.java

This is a wrapper around any existing failure failure. It simply works as a guard clause that will only delegate to the other failure handler if the number of retries has not be exceeded. 
Does the following equation to calculate the next execution time to retry the task. 
The default rate to use was stolen/borrowed from resilience4j project but is configurable to allow users to configure how much/less the backoff applies to the future executions. https://github.com/resilience4j/resilience4j/blob/03253134ac6f88954c8a65faa6dd7f92ed5e02f1/resilience4j-core/src/main/java/io/github/resilience4j/core/IntervalFunction.java#L20
This site is helpful to figure out what rate will be best for your situation. (not affiliated with this site just thought it was useful) …

Adds exponential backoff and max retries failure handlers

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ScheduledExecution.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/OnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleOnceOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleRecurringOnStartup.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/EmbeddedPostgresqlExtension.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MysqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutocommitTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/NoAutocommitTest.java

Transactions for `OnStartup` items (for example scheduling the initial `RecurringTask` instance) should be managed by the scheduler, i.e. should always commit. 
Fixes a bug where recurring-tasks were not scheduled on startup when using datasources that sets autocommit=false.

OnStartup items should always trigger commit.

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerActuatorAutoConfiguration.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerMetricsAutoConfiguration.java
db-scheduler-boot-starter/src/main/resources/META-INF/spring.factories
db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java

I recently found out that the Spring Boot starter implicitly requires [Actuator](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) to work. This PR changes the autoconfiguration so it will work both with and without Actuator on the classpath.

Don't require Spring Boot Actuator to work

---

README.md

Saw my former colleague updating the TransferWise description & decided to add a new company we are working on!
Very happy users of db-scheduler - it's one the core patterns in our codebase and has been scaling up flawlessly with us!

Add Lightyear to the README

---

README.md

Hey 
we have renamed from TransferWise to Wise some time ago 🙂 
so changing the readme to reflect  this

change transferwise to wise in the readme due to renaming

---

README.md

In production (2022.03.01): https://github.com/navikt/veilarbportefolje/pull/733

Update: 'Who uses db-scheduler?'

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ScheduleRecurringOnStartup.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/DisabledSchedule.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/DisabledScheduleParser.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/Schedules.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/DisabledCronTaskTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/CronTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/SchedulesTest.java
examples/features/src/main/java/com/github/kagkarlsson/examples/JobChainingPocMain.java

A Schedule for a RecurringTask can be marked as disabled. Will remove existing executions and not schedule new ones.

Support for disabled schedules

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
pom.xml

In preparation for [Spring Boot 3.0.0](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0) it is recommended to build against 2.7.0. This PR does just that.

Upgrade to Spring Boot 2.7.0

---

.github/workflows/ci.yml
db-scheduler/pom.xml

Reduces number of deprecation warnings. Also adds support for Java 17 (and possibly new versions in the future).

CI: Remove deprecated GitHub Actions

---

db-scheduler/src/test/resources/mssql_tables.sql
db-scheduler/src/test/resources/mysql_tables.sql
db-scheduler/src/test/resources/oracle_tables.sql
db-scheduler/src/test/resources/postgresql_tables.sql

Follow up on this issue #127 .
First of all, thanks for the great library.
We've faced this slow log issue when the number of rows reached around 3.5 million on MySQL (on db.t3.medium AWS RDS). Adding the two indices helped.
So it would be more scalable for others too if these indices were in the default schema.

Add indices to default schema

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/TaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/TriggerCheckForDueExecutions.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/ExecutionOperations.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
examples/features/src/main/java/com/github/kagkarlsson/examples/JobChainingUsingSeparateTasksMain.java
examples/features/src/main/java/com/github/kagkarlsson/examples/JobChainingUsingTaskDataMain.java

Enables JobChaining by replacing the old execution with the next step in the CompletionHandler.

Add support for ExecutionOperations.replace

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/RunUntilShutdown.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerState.java

Naive implementation of paused state
#353 
---

353 pause scheduler

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java

Shutdown heartbeating last to prevent execution classified as dead when stopping the execution is slow (since heartbeating already have stopped)

Shutdown heartbeating last

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java

Change supported Cron-expressions to Spring 5.3
#352
---

fix: Use Spring v5.3+ cron-style

---

.github/workflows/boot.yml
.github/workflows/pr.yml
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/FailureHandler.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
db-scheduler/src/test/resources/logback-test.xml

Updated failure handlers to use clock instead of `Instant.now()` (via ExecutionComplete)
#359

FailureHandlers should use timeDone Instant to calculate next try

---

db-scheduler/pom.xml
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/EmbeddedPostgresqlExtension.java

Replace opentable embedded postgres as they are moving to Docker.

refactor: replace opentable embedded postgres with zonky

---

.editorconfig
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/FailureHandler.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/FailureHandlerTest.java

Discussion ref.: #394 
Closes #396 
---

feat: add a maxRetriesExceededHandler to the MaxRetriesFailureHandler

---

.github/workflows/ci.yml
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerCustomizer.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/ManualScheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java

Candidate provided dueExecutor and houseKeeperExecutor. 
Issue: https://github.com/kagkarlsson/db-scheduler/issues/392
This helps db-scheduler work when applications use ThreadLocals or MDC. These applications have to implement custom thread pool or decorator patterns to manage state across threads. For just one example see `decorateTask` in ScheduledThreadPoolExecutor.
- N/A Update README and/or examples
---

feat: Candidate provided due and housekeeper executors

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ScheduledExecution.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ScheduledExecutionsFilter.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/TaskResolver.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/DataClassMismatchException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/MissingRawDataException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/ScheduledExecutionTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java
examples/features/pom.xml
examples/features/src/main/java/com/github/kagkarlsson/examples/SchedulerClientMain.java

If the `SchedulerClient` is instantiated with no _known tasks_, it currently does not find any executions since the client will not be able to resolve the task and will therefore filter them out. 
This PR **changes the behavior** of `getScheduledExecution()`, `getScheduledExecutions()` to also return unresolved executions, and additionally adds options in `ScheduledExecutionsFilter` to enable controlling whether or not to include them.

fix: getScheduledExecutions(...) should be able to return executions with unresolved tasks

---

README.md

Hello @kagkarlsson!
Nearly three years on from when we first started using db-scheduler, the library has scaled beautifully along with us, never causing a headache!
Now, we're a big-boy startup with the root domain lightyear.com. As a result, the old link will soon be obsolete.
Thank you once again for creating this library. We're planning to launch in Norway soon—just to get you onboard as a VIP customer! 😄 
Old PR for reference: https://github.com/kagkarlsson/db-scheduler/pull/268

docs: Update README with new Lightyear link

---

README.md

As happy users of db-scheduler we would like to add [Swan](https://www.swan.io/) in the list of users.
---

docs: Add Swan to the list of users

---

db-scheduler/src/test/resources/mssql_tables.sql

* Updated the MSSQL schema to not use the (deprecated) `text` data type.
* Use `varchar(5)` since, the max length is 50 according to https://github.com/kagkarlsson/db-scheduler/discussions/453
* Some alignment in casing and spacing
#454
---

fix: use varchar instead of (deprecated) text column type for MSSQL schema

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/DefaultJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepositoryContext.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MariaDBJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MssqlJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MySQL8JdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MySQLJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/OracleJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/PostgreSqlJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MariaDB103CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Mysql5CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Mysql8CompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutoCommitPostgresqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Oracle11gCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/PostgresqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/PostgresqlGenericFetchAndLockCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/ZoneSpecificJdbcCustomization.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/concurrent/PostgresClusterTest.java
db-scheduler/src/test/resources/oracle_tables.sql

* Update Oracle schema to use timezone-aware type
* Adds tests verifying that persisted instants are not affected by changes to JVM timezone
* Add configuration option to `JdbcCustomization` to allow users to explicitly choose to persist timestamps in UTC

fix: Update Oracle schema to use timezone-aware type

---

README.md
db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerProperties.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MariaDBJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MySQL8JdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MySQLJdbcCustomization.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/PostgresqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ExecutorPoolTest.java
pom.xml

Change back to default behavior for MySQL and MariaDB with regards to timestamp persistence and assumptions. It is recommended to persist timestamps in UTC for users of MariaDB and MySQL, but db-scheduler will not enforce it as default, since it in reality requires a controlled upgrade. 
Ideally the upgrade-process should be:
1. All instances of the scheduler should be shutdown
2. Timestamps in the database-table migrated to UTC
3. Configuration updated to use `alwaysPersistTimestampInUTC()`
4. Instances started again

fix: Revert change in behavior for MariaDB and MySQL with regards to time zone assumptions for persisted timestamps

---

db-scheduler-boot-starter/pom.xml
db-scheduler/pom.xml
examples/spring-boot-example/src/main/java/com/github/kagkarlsson/examples/boot/App.java

Add Automatic-Module-Name attribute to jar manifests for better Java 9+ JPMS compatibility. 
Affects: db-scheduler and db-scheduler-boot-starter.
Naturally the automatic module names I have entered are suggestions - please amend if required.
* Maven warning when compiling modular project: `Required filename-based automodules detected: [db-scheduler-13.0.0.jar]. Please don't publish this project to a public artifact repository!`
---

fix: Add Automatic-Module-Name attribute to jar manifests for better Java 9+ JPMS compatibility

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java

I've changed the Spring Boot auto-configuration to ensure that the `jdbcCustomization` default does not override the configured `alwaysPersistTimestampInUTC` default. The previous `orElse` part is not necessary because the correct `jdbcCustomization` default later gets applied in `SchedulerBuilder#build`.
Fixes #487 
- I don't know how to add an efficient test for this.
- I ran the tests but I got an unrelated error in an Oracle compatibility test, even without this change.
- I don't think this is relevant.
- This only changed unrelated code.
---

fix: Respect always-persist-timestamp-in-utc in Spring Starter (#487)

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java

Excludes DbSchedulerStarter from being lazily initialized.
The DbSchedulerStarter isn't created in a application where lazy initialization is enabled via `spring.main.lazy-initialization=true`.
Fixes: #491
---

fix: Eagerly load DBSchedulerStarter (491)

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java

fix: always set task_data via JdbcCustomization method

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExceptionUtils.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExecutePicked.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/ExceptionUtilsTest.java

A small suggestion for some improved ergonomics when reading log output from db-scheduler in the case of failures.
I always find it effective to include a small "summary" of any caught exception in the actual log message. Often this will allow me to pinpoint the error at hand without needing to look into the stacktrace of the logger event. (But this is still possible of course, as before)
Logs when exceptions propagates all the way back to db-scheduler can typically look like this:
This PR will change the log message to mention the actual exception which was caught in the log message:
> Unhandled exception IllegalArgumentException: 'Illegal character in path at index 9: [replace with URL]' during execution of task with name 'my-task-name'. Treating as failure.
No existing issue, I …

fix: Mention exception in log message on failures

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java

If the JDBC customization is already correctly configured, `SchedulerClient.Builder.build` should not instantiate an unused incorrectly configured one.
Instantiating a `SchedulerClient` on MariaDB always logged the UTC warning, even when using a correctly configured JDBC customization:
```java
SchedulerClient.Builder.create(dataSource)
.jdbcCustomization(AutodetectJdbcCustomization(dataSource, true))
.build()
```
```
2024-06-21T15:44:33.427+02:00  WARN 57277 --- [  restartedMain] c.g.k.s.j.A.utc_warning                  : MariaDB-schema does not support persistent timezones. It is recommended to store time in UTC to avoid issues with for example DST. For first time users, use setting 'alwaysPersistTimestampInUtc' to achieve this. Users upgrading from a version prior to v14.0.0 can either …
```

fix: Avoid false warning about UTC timestamps

---

db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/DbUtils.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Oracle11gCompatibilityTest.java
db-scheduler/src/test/resources/oracle_tables.sql

Every example for other databases (Postgres, Mssql, Mysql) contains indexes on `execution_time` and `last_heartbeat` while for Oracle DB they are missing.
I also expanded `DbUtiils` method to allow splitting sql statements from an sql file. `jdbcRunner.execute(statement, NOOP)` can run only one statement at a time for Oracle Db.
PS: two tests for oracle db are failing on master, is that expected?
- no need
---

feat: add missing indexes to the oracle ddl script

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java

Rename `client.schedule(...)` method to `client.scheduleIfNotExists(...)` to clarify default but slightly hidden behavior where nothing is scheduled if the instance already exists.
Deprecated old `client.schedule(...)` methods.
Fixes  #326

feat: rename client.schedule(..) to clarify hidden behavior where nothing is scheduled if the instance already exists

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java

The `DbSchedulerAutoConfiguration#eagerDbSchedulerStarter` must be declared as static to ensure it is available before the `initialization` of `DbSchedulerAutoConfiguration`. Spring Boot will otherwise try to instantiate the `DbSchedulerAutoConfiguration` class using a no-args constructor.
> NOTE: Beans of this type will be instantiated very early in the spring application lifecycle so they should generally be declared static and not have any dependencies.
https://docs.spring.io/spring-boot/api/java/org/springframework/boot/LazyInitializationExcludeFilter.html#:~:text=NOTE%3A%20Beans%20of%20this%20type%20will%20be%20instantiated%20very%20early%20in%20the%20spring%20application%20lifecycle%20so%20they%20should%20generally%20be%20declared%20static%20and%20not%20have%20any%20dependencies. …

fix: 511 - Declare DbSchedulerAutoConfiguration#eagerDbSchedulerStarter as static

---

pom.xml

Upgrade logback from 1.2.12 to 1.2.13 to resolve CVEs in 1.2.12
https://github.com/kagkarlsson/db-scheduler/issues/542
---

chore(deps): upgrade logback to 1.2.13

---

examples/spring-boot-example/src/test/java/com/github/kagkarlsson/examples/boot/SmokeTest.java

Fixed one typo in a test file. 
---

Fixed typo in the log msg of the SmokeTest class

---

README.md

PR fixes the broken `postgresql_tables.sql` reference in `README.md` because of missing "d" in `db-scheduler`. Also it fixes a few typos on the way.
---

fix: update `postgresql_tables.sql` reference

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MariaDBJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MssqlJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MySQL8JdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/OracleJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/PostgreSqlJdbcCustomization.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/Queries.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Mysql8CompatibilityTest.java

The support was nearly finished in #371 but later commented out due to "some issue [..] and limited time".
I tried to find out what those issues were and discovered that the syntax of the select was wrong. In MySQL the `LIMIT` comes before the `FOR UPDATE SKIP LOCKED`.
Using that fix `Mysql8CompatibilityTest` passes, I have done no further testing yet.
#264
---

feat: fix lock-and-fetch for MySQL

---

README.md

There was a typo in the latest documentation
The typo gets fixed
---

fix typo in links

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/CronTest.java

Adding Equals and HasCode for CronSchedule
---

fix: Adding equals and hashcode for CronSchedule

---

db-scheduler/src/test/resources/mssql_tables.sql

Adjusting primary-key order for SQL Server to reduce deadlocking after analysis and testing presented in #527
#527

fix: Adjusting primary-key order for SQL Server to reduce deadlocking

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java

Making fields protected so that we can access in custom SchedulerBuilder
---

fix: Making fields protected in SchedulerBuilder

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java

When invoking SchedulerClient.reschedule() with a non-existent TaskInstance, an exception will be raised. Therefore, it's essential to verify the existence of a scheduled TaskInstance prior to attempting a reschedule. To streamline this process, we propose the introduction of a scheduleOrCreate method. This method would automatically schedule a TaskInstance if none exists, making it particularly beneficial for dynamically recurring tasks that require initial setup.
We have given considerable thought to finding an appropriate name for this method, but unfortunately, we haven't arrived at a satisfactory conclusion. The verb "schedule" best describes its functionality; however, it cannot be used as there is already a method with that name. Since "rescheduleOrSchedule" sounds awkward, we have …

feat: Add schedule-or-reschedule method to the SchedulerClient

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/AbstractTask.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/AbstractTaskTest.java

Include the default priority of a task class when creating an instance without data
#604 
---

fix: recurring tasks get correct default priority without data (#604)

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/DeadExecutionHandler.java

This is a one liner to use the correct logger in the `CancelDeadExecution` class.
---

Use correct logger for CancelDeadExecution

---

README.md
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/AbstractTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/Task.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/OneTimeTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTaskWithPersistentSchedule.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/Tasks.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/RecurringTaskScheduleTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/helper/CustomTaskTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/helper/OneTimeTaskTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTaskTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTaskWithPersistentScheduleTest.java

This PR makes it possible to set a default priority for all built-in task types.
This makes it possible to e.g. define recurring tasks that only will run when the queue is otherwise empty.
---

feat: set default priority

---

.github/workflows/ci.yml
README.md
db-scheduler/pom.xml
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/StreamUtils.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/TaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/DbSchedulerException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/FailedToScheduleBatchException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/TaskInstanceException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/ScheduledTaskInstance.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java
examples/features/src/main/java/com/github/kagkarlsson/examples/SchedulerClientMain.java
jreleaser.yml

This PR adds support for scheduling new tasks using batch inserts.
Known issues:
- Updates are not supported; if any of the tasks in a batch exists, the batch will fail
- Hard-coded batch size of 100 when using `Stream` as parameter. Inserts are committed after each batch.
#595

feat: Support for batch scheduling

---

README.md

Fixes the Spring Boot configuration docs in the `README` for polling strategy to reflect updated properties.
Closes #629.
---

629: update Spring Boot configuration docs for polling strategy

---

db-scheduler-boot-starter/pom.xml

fix: Compile with -parameters flag

---

db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/concurrent/MssqlClusterTest.java
db-scheduler/src/test/resources/container-license-acceptance.txt

Fix build-errors caused by docker-image not starting on newer Ubuntu-images for github runners

fix: Upgrade Sql Server image used in tests

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java

See issue #654. This fix reduces that logging from WARN to DEBUG. If there are consecutive failures for heartbeats, there will still be a WARN (handled on the outside)
Fixes #654

fix: Reduce log-level to DEBUG when missing a single heartbeat update

---

db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/helper/TimeHelper.java

getExecutionsFailingLongerThan is not working as expected. Returns execution forever if it has failed once..
#563

fix: Fix getExecutionsFailingLongerThan to not return executions that have previously failed but are now running ok

---

.github/workflows/ci.yml
.github/workflows/release.yml
.sdkmanrc
CONTRIBUTING.md
README.md
db-scheduler-boot-starter/pom.xml
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExecutePicked.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/FetchCandidates.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/DataClassMismatchException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/DbSchedulerException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/ExecutionException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/FailedToScheduleBatchException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/MissingRawDataException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/SerializationException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/TaskInstanceCurrentlyExecutingException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/TaskInstanceException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/exceptions/TaskInstanceNotFoundException.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/PlainScheduleAndData.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CompositeParser.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/Daily.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/FixedDelay.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/PersistentCronSchedule.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/ScheduledExecutionTest.java
db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/serializer/jackson/ScheduleAndDataForTest.java
examples/features/pom.xml
examples/spring-boot-example/src/main/java/com/github/kagkarlsson/examples/boot/config/MultiInstanceRecurringConfiguration.java
examples/spring-boot-example/src/main/java/com/github/kagkarlsson/examples/boot/config/ParallellJobConfiguration.java
pom.xml

I used https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17 to perform the migration from Java 11 to Java 17. In addition I added an migration guide, since this will be a breaking change. 
Fixes https://github.com/kagkarlsson/db-scheduler/issues/681
---

build: Update to Java 17

---

db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java

- Added clock(Clock) method to SchedulerBuilder so users can provide their own clock for Scheduler
- In order not to have to think about Waiter caching old Clock I moved Waiter creation to build method, so it always uses latest Clock from builder field
- Had to build Waiter manually in TestHelper for ManualScheduler.
Note: This changes current behavior, but I think it's a bug. 
Currently Waiter in ManualScheduler is using SystemClock instead of newly set clock, I changed that because Waiter is now created in the end so it will always use up-to date Clock instance, in case this is desired behavior for some reason, let me know and I will fix it. 
---

feat: Expose Clock from builder and implement in Spring Boot AutoConfiguration

---

db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
pom.xml

Upgrade support to Spring Boot 3.5.5.
#735 
---

build(deps): Use Spring Boot v3.5.5 as default (from 3.4.5)
