- src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
- src/main/java/com/github/kagkarlsson/scheduler/task/Task.java
- src/main/java/com/github/kagkarlsson/scheduler/task/TaskInstance.java
- src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
- src/test/resources/hsql_tables.sql
- src/test/resources/mysql_tables.sql
- src/test/resources/oracle_tables.sql
- src/test/resources/postgresql_tables.sql
Alternate suggestion for #5 using byte[] as state instead of String
> Store state as byte[] together with task instance. #5

- src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
- src/main/java/com/github/kagkarlsson/scheduler/task/ExecutionHandler.java
- src/main/java/com/github/kagkarlsson/scheduler/task/OneTimeTask.java
- src/main/java/com/github/kagkarlsson/scheduler/task/RecurringTask.java
- src/main/java/com/github/kagkarlsson/scheduler/task/Task.java
- src/main/java/com/github/kagkarlsson/scheduler/task/TaskInstance.java
- src/test/java/com/github/kagkarlsson/scheduler/TestTasks.java
- src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
- src/test/java/com/github/kagkarlsson/scheduler/example/TasksMain.java
See https://github.com/kagkarlsson/db-scheduler/issues/5#issuecomment-296817502 #5
> Tasks where made type safe.

- README.md
- src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
- src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
- src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
- src/test/java/com/github/kagkarlsson/scheduler/CustomTableNameTest.java
- src/test/java/com/github/kagkarlsson/scheduler/DbUtils.java
- src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java
- src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
- src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java
- src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
- src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
- src/test/resources/com/github/kagkarlsson/scheduler/postgresql_custom_tablename.sql
Customize table name by using `tableName(…)` upon configuration of
`Scheduler`.
> Allows for customization of table name

- NOTICE
- pom.xml
- src/test/java/com/github/kagkarlsson/scheduler/MssqlTestDatabaseRule.java
- src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
- src/test/resources/mssql_tables.sql
Table script and Compatibility Test
> add mssql table definition

- src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
- src/main/java/com/github/kagkarlsson/scheduler/testhelper/ManualScheduler.java
- src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
- src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java
- src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
> Allow check for new due executions after completing picked tasks

- README.md
- db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
- db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java
- pom.xml
> Allow for custom DbSchedulerStarter bean

- .travis.yml
- README.md
- db-scheduler-boot-starter/pom.xml
- db-scheduler-boot-starter/src/test/resources/logback-test.xml
- db-scheduler/pom.xml
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/AutodetectJdbcCustomization.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/DefaultJdbcCustomization.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcCustomization.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/MssqlJdbcCustomization.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/CustomTableNameTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MysqlCompatibilityTest.java
- db-scheduler/src/test/resources/container-license-acceptance.txt
- db-scheduler/src/test/resources/logback-test.xml
- db-scheduler/src/test/resources/mysql_tables.sql
- db-scheduler/src/test/resources/simplelogger.properties
- examples/spring-boot-example/pom.xml
- examples/spring-boot-example/src/main/resources/application.properties
- examples/spring-boot-example/src/main/resources/schema.sql
- examples/spring-boot-example/src/test/resources/logback-test.xml
- pom.xml
* Fix bug in timestamp handling in prepared statement setter for mssql. 
* Adding compatibility tests for mysql and mssql based on testcontainers.
* Adding `logback-test.xml` from PR #92 by dpratt
> Fix bug in timestamp handling in prepared statement setter for mssql

- README.md
I started on a list of known users of db-scheduler. What do you @kagkarlsson?
> Add list of known users

- README.md
Hey Gustav + all!
Thanks so much for writing this library!
We've been using it for a good year in production at TransferWise & it's use has quickly expanded to a handful of services and a handful of different use cases and this library has never let us down or gotten in the way!
> Add TransferWise to list of users

- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ExecutorPoolTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/helper/ExecutionCompletedCondition.java
- pom.xml
Provide sources for shaded dependency cronutils
> Provide sources for shaded dependency cronutils

- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java
Closes #135 
Adding basic javadoc to SchedulerClient class. Not finished yet, just saving the progress
> Adding javadoc to SchedulerClient class

- .github/workflows/ci.yml
- db-scheduler/pom.xml
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/CompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/helper/TimeHelper.java
This PR will ensure that all tests will checked against AdoptOpenJDK 15 as well. Bumped `equalsverifier`, since it wasn't compatible with Java 15.
> Java 15 compatibility

- README.md
We are very happy with db-scheduler. Thank you!
> Adding Monitoria to the list of companies using db-scheduler

- db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/AbstractTask.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/Task.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/ComposableTask.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/OneTimeTask.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/TestHelper.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/DeadExecutionsTest.java
- examples/spring-boot-example/src/test/java/com/github/kagkarlsson/examples/boot/SmokeTest.java
> Ability to decorate task execution

- README.md
This scheduler is working great for us at Loadster and we'd like to be added to the list! Happily running in production for over a month now and a big improvement over our old task scheduler. Thanks @kagkarlsson.
> Add Loadster to the list of companies using db-scheduler.

- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ClientEvent.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExecutePicked.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/FetchCandidates.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/LockAndFetchCandidates.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/ExecutionOperations.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/TestSchedules.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ImmediateExecutionTest.java
Immediate execution should work for rescheduling in completionhandler
Fixes #297
> Immediate execution should work for rescheduling in completionhandler

- .github/workflows/boot.yml
- db-scheduler-boot-starter/pom.xml
- db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/startup/ImmediateStart.java
- db-scheduler-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MysqlCompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutoCommitPostgresqlCompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/NoAutocommitTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/Oracle11gCompatibilityTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/functional/ExecutorPoolTest.java
- pom.xml
This PR adds support for the upcoming Spring Boot 3.0 support as well as having backward compatibility. A new GitHub Action is added for continuously integrating with various Spring Boot versions.
> Spring Boot 3.0 support

- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/PlainScheduleAndData.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/schedule/CronSchedule.java
fixed this issue https://github.com/kagkarlsson/db-scheduler/issues/334
> Fix CronSchedule.java Serializable

- .github/workflows/boot.yml
- db-scheduler-boot-starter/pom.xml
- db-scheduler/pom.xml
- examples/features/pom.xml
- examples/spring-boot-example/pom.xml
- pom.xml
Refactor dependency-management for better spring-boot compatibility
> refactor: Refactor dependency-management for better spring-boot compatibility

- db-scheduler/pom.xml
- pom.xml
Upgrades dependencies:
* cron-utils
* hsqldb
* equals-verifier
* bytebuddy
* zonky-pg-embedded
* micrometer
* gson
* jackson
* postgresql
* guava
> build(maven): Version upgrades

- .github/workflows/ci.yml
- .sdkmanrc
- db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/task/schedule/CompositeParserTest.java
- pom.xml
> feat: Remove Java 8 support

- .github/workflows/boot.yml
- examples/spring-boot-example/src/main/java/com/github/kagkarlsson/examples/boot/App.java
- pom.xml
Updates the spring-boot-compatibility workflow with the latest spring boot versions.
See https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention
---
> build(deps): Updates the spring-boot-compatibility workflow with the latest spring boot versions.

- README.md
Added TOMRA as user of db-scheduler
- [✅] Added/ran automated tests
- [✅] Update README and/or examples
- [✅] Ran `mvn spotless:apply`
---
> docs: Added TOMRA as user

- README.md
Readme is updated according to #526 
> Add osoykan/db-scheduler-additions sections to the 3rd party list

- .github/workflows/boot.yml
- .github/workflows/ci.yml
- .github/workflows/pr-lint.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Likely related to this [issue](https://github.com/actions/runner-images/issues/10649).
> chore(ci): Downgrade to Github Actions runner ubuntu-20.04 to avoid SQL Server problems

- db-scheduler/src/test/resources/oracle_tables.sql
Updated the name of index(removed extra underscore)
---
> docs: Update oracle_tables.sql

- db-scheduler/pom.xml
- pom.xml
> chore(deps): bump versions

- db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java
- db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/config/DbSchedulerCustomizer.java
> feat: Extend DBSchedulerCustomizer with datasource method

- db-scheduler/pom.xml
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/BatchPreparedStatementSetter.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/ConnectionSupplier.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/DataSourceConnectionSupplier.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/DoInTransaction.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/ExternallyManagedConnection.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/IntegrityConstraintViolation.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/JdbcRunner.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/Mappers.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/PreparedStatementExecutor.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/PreparedStatementSetter.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/ResultSetMapper.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/RowMapper.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/SQLRuntimeException.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/ThreadLocalTransactionContextProvider.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/TransactionContext.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/TransactionContextProvider.java
- db-scheduler/src/main/java/com/github/kagkarlsson/jdbc/TransactionManager.java
- db-scheduler/src/test/java/com/github/kagkarlsson/jdbc/CommitWhenAutocommitDisabledTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/jdbc/HsqlExtension.java
- db-scheduler/src/test/java/com/github/kagkarlsson/jdbc/JdbcRunnerTest.java
- db-scheduler/src/test/java/com/github/kagkarlsson/jdbc/TransactionManagerTest.java
- examples/features/pom.xml
- examples/features/src/main/java/com/github/kagkarlsson/examples/HeartbeatMonitoringMain.java
- pom.xml
Rather than maintaining it as a separate project, inline it to simplify both maintenance and understanding.
> feat: Inline micro jdbc

- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java
- db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerState.java
Allows thread-safe modification of the pause flag
---
> Thread safe pausing
